server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/docsea_1
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

DOCSEAPATH : ../client/src/assets/images/